const constants = {
    ADD_THREAD: "ADD_THREAD",
    EDIT_THREAD:"EDIT_THREAD",
    DELETE_THREAD:"DELETE_THREAD",
    FETCH_THREADS:"FETCH_THREADS",
    FETCH_THREADS_SUCCESS:"FETCH_THREADS_SUCCESS",
    FETCH_THREADS_ERROR:"FETCH_THREADS_ERROR",

    ADD_COMMENT: "ADD_COMMENT",
    EDIT_COMMENT:"EDIT_COMMENT",
    DELETE_COMMENT:"DELETE_COMMENT",
    FETCH_COMMENTS:"FETCH_COMMENTS",
    FETCH_COMMENTS_SUCCESS:"FETCH_COMMENTS_SUCCESS",
    FETCH_COMMENTS_ERROR:"FETCH_COMMENTS_ERROR",

    ADD_USER:"ADD_USER",
    EDIT_USER:"EDIT_USER",
    DELETE_USER:"DELETE_USER",

    FETCH_PROFILE:"FETCH_PROFILE",
    FETCH_PROFILE_SUCCESS:"FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_ERROR:"FETCH_PROFILE_ERROR",
    CLEAR_PROFILE:"CLEAR_PROFILE",

    LOGIN_REQUEST:"LOGIN_REQUEST",
    AUTHENTICATED:'AUTHENTICATED',
    UNAUTHENTICATED :'UNAUTHENTICATED',
    LOGOUT:"LOGOUT",
    RESET:"RESET"

};

export default constants